name: Auto Update Version

on:
  push:
    branches:
      - main

jobs:
  update_version:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Update Version
      id: update_version_step
      run: echo "::set-output name=new_version::$(python update_version.py)" 

    - name: Commit and tag
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -m "Bump version to ${{ steps.update_version_step.outputs.new_version }}" # Use the output from the step
        git tag ${{ steps.update_version_step.outputs.new_version }} # Use the output from the step
        git push origin main --tags
