name: Update Version

on:
  push:
    branches:
      - main

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Run update_version.py
      run: python scripts/update_version.py

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add modules/__init__.py
        git commit -m "Update version"
        git push
